services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: secret_pass
            POSTGRES_DB: quizsite
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - 5432:5432
            

    # backend:
    #     image: quiz-backend
    #     build: ./backend
    #     ports:
    #         - 9595:9595
    #     environment:
    #         PORT: 9595
    #         SESSION_SECRET: 734bv8#f49!wev/4ne47#jcf78
    #         PGDATABASE: quizsite
    #         PGHOST: postgres
    #         PGUSER: postgres
    #         PGPASSWORD: secret_pass
    #         DATABASE_URL: postgresql://postgres:secret_pass@localhost:5432/quizsite?schema=public
    #     depends_on: 
    #         postgres:
    #             condition: service_healthy

volumes:
    pgdata: